name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build the Docker Image
        run: docker build --no-cache --pull -t herrtxbias/utilbot-docs:${{ steps.get_version.outputs.VERSION }} -t herrtxbias/utilbot-docs:latest .
      
      - name: Push the Docker Image
        run: docker push herrtxbias/utilbot-docs:${{ steps.get_version.outputs.VERSION }}
        
      - name: Push the Docker Image
        run: docker push herrtxbias/utilbot-docs:latest
        
      - name: Update Image in Swarm
        uses: fjogeleit/http-request-action@master
        with:
          url: '${{ secrets.PORTAINER_WEBHOOK }}'
          method: 'POST'
